# Creation of Array(1D ,2D and Multidimensional array)

In [1]:
#Exp no.:5

In [2]:
#Aim : Creation of Array (1D,2D and Multidimennsional array) using numpy

In [3]:
#Name:Nikhil Pavan Agrawal
#Roll No:02
#Sec:B
#Subject:ET1
#Date:21/08/2025

In [4]:
import numpy as np

In [7]:
arr1=np.array([10,20,30,40,50])

In [8]:
arr1

array([10, 20, 30, 40, 50])

In [9]:
arr2=np.array([[10,20,30,40,50],[60,70,80,90,100]])

In [10]:
arr2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [11]:
arr3=np.array([[10,20,30,40,50],[60,70,80,90,100],[15,25,35,45,55]])

In [12]:
arr3

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [ 15,  25,  35,  45,  55]])

In [13]:
# Array of zeros
zeros_arr = np.zeros((2, 3))
print("Zeros Array:\n", zeros_arr)

# Array of ones
ones_arr = np.ones((3, 3))
print("Ones Array:\n", ones_arr)

# Identity matrix
identity_arr = np.eye(3)
print("Identity Matrix:\n", identity_arr)

# Range of numbers
range_arr = np.arange(0, 10, 2)
print("Array with np.arange:\n", range_arr)

# Evenly spaced values
linspace_arr = np.linspace(0, 1, 5)
print("Array with np.linspace:\n", linspace_arr)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array with np.arange:
 [0 2 4 6 8]
Array with np.linspace:
 [0.   0.25 0.5  0.75 1.  ]


In [14]:
print("Shape of arr2d:", arr2.shape)
print("Size of arr2d:", arr2.size)
print("Data type of arr2d:", arr2.dtype)

Shape of arr2d: (2, 5)
Size of arr2d: 10
Data type of arr2d: int64


In [16]:
reshaped = arr2.reshape(2, 5)
print("Reshaped Array:\n", reshaped)

# Slicing
print("First row of arr2d:", arr2[0])
print("Element at row 1, col 2:", arr2[1, 2])

Reshaped Array:
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
First row of arr2d: [10 20 30 40 50]
Element at row 1, col 2: 80


In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Multiplication:", a * b)
print("Square root:", np.sqrt(a))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Square root: [1.         1.41421356 1.73205081]


# Conclusion :
             The experiment successfully demonstrated the creation and manipulation of 1D, 2D, and multi-dimensional arrays, which are fundamental structures in data science and statistics. Mastery of these array types is essential for efficient data handling, analysis, and computational operations.